#region Namespace Sonata.Diagnostics.Logging.Schema
//	TODO
#endregion

using System.Xml.Serialization;

namespace Sonata.Diagnostics.Logging.Schema
{
	//------------------------------------------------------------------------------
	// <auto-generated>
	//     This code was generated by a tool.
	//     Runtime Version:4.0.30319.42000
	//
	//     Changes to this file may cause incorrect behavior and will be lost if
	//     the code is regenerated. 
	// </auto-generated>
	//------------------------------------------------------------------------------
	// 
	// This source code was auto-generated by xsd, Version=4.7.2558.0.
	// 


	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlRoot(Namespace = "", IsNullable = false)]
	public partial class log4net
	{

		private object[] itemsField;

		private bool debugField;

		private log4netUpdateAttribute updateField;

		private log4netLevel thresholdField;

		public log4net()
		{
			this.debugField = false;
			this.updateField = log4netUpdateAttribute.Merge;
			this.thresholdField = log4netLevel.ALL;
		}

		/// <remarks/>
		[XmlElement("appender", typeof(appender), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("logger", typeof(logger), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("param", typeof(param), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("renderer", typeof(renderer), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("root", typeof(root), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public object[] Items
		{
			get { return this.itemsField; }
			set { this.itemsField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		[System.ComponentModel.DefaultValueAttribute(false)]
		public bool debug
		{
			get { return this.debugField; }
			set { this.debugField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		[System.ComponentModel.DefaultValueAttribute(log4netUpdateAttribute.Merge)]
		public log4netUpdateAttribute update
		{
			get { return this.updateField; }
			set { this.updateField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		[System.ComponentModel.DefaultValueAttribute(log4netLevel.ALL)]
		public log4netLevel threshold
		{
			get { return this.thresholdField; }
			set { this.thresholdField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class appender
	{

		private object[] itemsField;

		private string nameField;

		private log4netAppenderTypes typeField;

		/// <remarks/>
		[XmlElement("appendToFile", typeof(appendToFile), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("appender-ref", typeof(appender_ref), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("applicationName", typeof(applicationName), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("authentication", typeof(authentication), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("bufferSize", typeof(bufferSize), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("commandText", typeof(commandText), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("commandType", typeof(commandType), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("connectionString", typeof(connectionString), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("connectionType", typeof(connectionType), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("countDirection", typeof(countDirection), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("datePattern", typeof(datePattern), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("encoding", typeof(encoding), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("evaluator", typeof(evaluator), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("facility", typeof(facility), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("file", typeof(file), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("filter", typeof(filter), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("from", typeof(from), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("identity", typeof(identity), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("immediateFlush", typeof(immediateFlush), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("layout", typeof(layout), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("localPort", typeof(localPort), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("lockingModel", typeof(lockingModel), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("logName", typeof(logName), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("lossy", typeof(lossy), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("machineName", typeof(machineName), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("mapping", typeof(mapping), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("maxFileSize", typeof(maxFileSize), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("maxSizeRollBackups", typeof(maxSizeRollBackups), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("maximumFileSize", typeof(maximumFileSize), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("param", typeof(param), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("parameter", typeof(parameter), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("password", typeof(password), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("pickupDir", typeof(pickupDir), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("port", typeof(port), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("priority", typeof(priority), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("recipient", typeof(recipient), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("reconnectOnError", typeof(reconnectOnError), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("remoteAddress", typeof(remoteAddress), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("remotePort", typeof(remotePort), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("rollingStyle", typeof(rollingStyle), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("securityContext", typeof(securityContext), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("sender", typeof(sender), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("server", typeof(server), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("sink", typeof(sink), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("smtpHost", typeof(smtpHost), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("staticLogFileName", typeof(staticLogFileName), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("subject", typeof(subject), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("target", typeof(target), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("threshold", typeof(threshold), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("to", typeof(to), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("useTransactions", typeof(useTransactions), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("username", typeof(userName), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public object[] Items
		{
			get { return this.itemsField; }
			set { this.itemsField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string name
		{
			get { return this.nameField; }
			set { this.nameField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public log4netAppenderTypes type
		{
			get { return this.typeField; }
			set { this.typeField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class appendToFile
	{

		private bool valueField;

		/// <remarks/>
		[XmlAttribute()]
		public bool value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class connectionType
	{

		private connectionTypeTypes valueField;

		/// <remarks/>
		[XmlAttribute()]
		public connectionTypeTypes value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	public enum connectionTypeTypes
	{

		/// <remarks/>
		[XmlEnum("System.Data.OleDb.OleDbConnection, System.Data")]
		SystemDataOleDbOleDbConnectionSystemData,

		/// <remarks/>
		[XmlEnum("System.Data.SqlClient.SqlConnection, System.Data")]
		SystemDataSqlClientSqlConnectionSystemData,

		/// <remarks/>
		[XmlEnum("Microsoft.Data.Odbc.OdbcConnection, Microsoft.Data.Odbc")]
		MicrosoftDataOdbcOdbcConnectionMicrosoftDataOdbc,

		/// <remarks/>
		[XmlEnum("System.Data.OracleClient.OracleConnection, System.Data.OracleClient")]
		SystemDataOracleClientOracleConnectionSystemDataOracleClient,

		/// <remarks/>
		[XmlEnum("MySql.Data.MySqlClient.MySqlConnection, MySql.Data")]
		MySqlDataMySqlClientMySqlConnectionMySqlData,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class connectionString
	{

		private string valueField;

		/// <remarks/>
		[XmlAttribute()]
		public string value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class commandType
	{

		private CommandType valueField;

		/// <remarks/>
		[XmlAttribute()]
		public CommandType value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	public enum CommandType
	{

		/// <remarks/>
		Text,

		/// <remarks/>
		StoredProcedure,

		/// <remarks/>
		TableDirect,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class commandText
	{

		private string valueField;

		/// <remarks/>
		[XmlAttribute()]
		public string value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class evaluator
	{

		private threshold thresholdField;

		private evaluatorTypes typeField;

		/// <remarks/>
		[XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public threshold threshold
		{
			get { return this.thresholdField; }
			set { this.thresholdField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public evaluatorTypes type
		{
			get { return this.typeField; }
			set { this.typeField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class threshold
	{

		private log4netLevel valueField;

		/// <remarks/>
		[XmlAttribute()]
		public log4netLevel value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	public enum log4netLevel
	{

		/// <remarks/>
		ALL,

		/// <remarks/>
		DEBUG,

		/// <remarks/>
		INFO,

		/// <remarks/>
		WARN,

		/// <remarks/>
		ERROR,

		/// <remarks/>
		FATAL,

		/// <remarks/>
		OFF,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	public enum evaluatorTypes
	{

		/// <remarks/>
		[XmlEnum("log4net.Core.LevelEvaluator")]
		log4netCoreLevelEvaluator,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class lossy
	{

		private bool valueField;

		/// <remarks/>
		[XmlAttribute()]
		public bool value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class bufferSize
	{

		private int valueField;

		/// <remarks/>
		[XmlAttribute()]
		public int value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class domain
	{

		private string valueField;

		/// <remarks/>
		[XmlAttribute()]
		public string value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class securityContext
	{

		private userName userNameField;

		private password passwordField;

		private domain domainField;

		private securityContextTypes typeField;

		/// <remarks/>
		[XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public userName userName
		{
			get { return this.userNameField; }
			set { this.userNameField = value; }
		}

		/// <remarks/>
		[XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public password password
		{
			get { return this.passwordField; }
			set { this.passwordField = value; }
		}

		/// <remarks/>
		[XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public domain domain
		{
			get { return this.domainField; }
			set { this.domainField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public securityContextTypes type
		{
			get { return this.typeField; }
			set { this.typeField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class userName
	{

		private string valueField;

		/// <remarks/>
		[XmlAttribute()]
		public string value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class password
	{

		private string valueField;

		/// <remarks/>
		[XmlAttribute()]
		public string value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	public enum securityContextTypes
	{

		/// <remarks/>
		[XmlEnum("log4net.Util.NullSecurityContext")]
		log4netUtilNullSecurityContext,

		/// <remarks/>
		[XmlEnum("log4net.Util.WindowsSecurityContext")]
		log4netUtilWindowsSecurityContext,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class regexToMatch
	{

		private string valueField;

		/// <remarks/>
		[XmlAttribute()]
		public string value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class stringToMatch
	{

		private string valueField;

		/// <remarks/>
		[XmlAttribute()]
		public string value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class loggerToMatch
	{

		private string valueField;

		/// <remarks/>
		[XmlAttribute()]
		public string value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class acceptOnMatch
	{

		private bool valueField;

		/// <remarks/>
		[XmlAttribute()]
		public bool value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class levelMin
	{

		private log4netLevel valueField;

		/// <remarks/>
		[XmlAttribute()]
		public log4netLevel value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class levelToMatch
	{

		private log4netLevel valueField;

		/// <remarks/>
		[XmlAttribute()]
		public log4netLevel value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class levelMax
	{

		private log4netLevel valueField;

		/// <remarks/>
		[XmlAttribute()]
		public log4netLevel value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class filter
	{

		private object[] itemsField;

		private log4netFilterTypes typeField;

		/// <remarks/>
		[XmlElement("acceptOnMatch", typeof(acceptOnMatch), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("key", typeof(key), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("levelMax", typeof(levelMax), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("levelMin", typeof(levelMin), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("levelToMatch", typeof(levelToMatch), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("loggerToMatch", typeof(loggerToMatch), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("param", typeof(param), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("regexToMatch", typeof(regexToMatch), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("stringToMatch", typeof(stringToMatch), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public object[] Items
		{
			get { return this.itemsField; }
			set { this.itemsField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public log4netFilterTypes type
		{
			get { return this.typeField; }
			set { this.typeField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class key
	{

		private string valueField;

		/// <remarks/>
		[XmlAttribute()]
		public string value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class param
	{

		private param[] param1Field;

		private string nameField;

		private string valueField;

		private string typeField;

		/// <remarks/>
		[XmlElement("param", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public param[] param1
		{
			get { return this.param1Field; }
			set { this.param1Field = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string name
		{
			get { return this.nameField; }
			set { this.nameField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string type
		{
			get { return this.typeField; }
			set { this.typeField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	public enum log4netFilterTypes
	{

		/// <remarks/>
		[XmlEnum("log4net.Filter.DenyAllFilter")]
		log4netFilterDenyAllFilter,

		/// <remarks/>
		[XmlEnum("log4net.Filter.LevelMatchFilter")]
		log4netFilterLevelMatchFilter,

		/// <remarks/>
		[XmlEnum("log4net.Filter.LevelRangeFilter")]
		log4netFilterLevelRangeFilter,

		/// <remarks/>
		[XmlEnum("log4net.Filter.LoggerMatchFilter")]
		log4netFilterLoggerMatchFilter,

		/// <remarks/>
		[XmlEnum("log4net.Filter.MdcFilter")]
		log4netFilterMdcFilter,

		/// <remarks/>
		[XmlEnum("log4net.Filter.NdcFilter")]
		log4netFilterNdcFilter,

		/// <remarks/>
		[XmlEnum("log4net.Filter.PropertyFilter")]
		log4netFilterPropertyFilter,

		/// <remarks/>
		[XmlEnum("log4net.Filter.StringMatchFilter")]
		log4netFilterStringMatchFilter,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class maxSizeRollBackups
	{

		private int valueField;

		/// <remarks/>
		[XmlAttribute()]
		public int value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class remotePort
	{

		private int valueField;

		/// <remarks/>
		[XmlAttribute()]
		public int value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class remoteAddress
	{

		private string valueField;

		/// <remarks/>
		[XmlAttribute()]
		public string value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class localPort
	{

		private int valueField;

		/// <remarks/>
		[XmlAttribute()]
		public int value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class pickupDir
	{

		private string valueField;

		/// <remarks/>
		[XmlAttribute()]
		public string value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class port
	{

		private int valueField;

		/// <remarks/>
		[XmlAttribute()]
		public int value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class smtpHost
	{

		private string valueField;

		/// <remarks/>
		[XmlAttribute()]
		public string value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class authentication
	{

		private authenticationTypes valueField;

		/// <remarks/>
		[XmlAttribute()]
		public authenticationTypes value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	public enum authenticationTypes
	{

		/// <remarks/>
		None,

		/// <remarks/>
		Basic,

		/// <remarks/>
		Ntlm,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class to
	{

		private string valueField;

		/// <remarks/>
		[XmlAttribute()]
		public string value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class subject
	{

		private string valueField;

		/// <remarks/>
		[XmlAttribute()]
		public string value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class priority
	{

		private priorityTypes valueField;

		/// <remarks/>
		[XmlAttribute()]
		public priorityTypes value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	public enum priorityTypes
	{

		/// <remarks/>
		Normal,

		/// <remarks/>
		Low,

		/// <remarks/>
		High,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class from
	{

		private string valueField;

		/// <remarks/>
		[XmlAttribute()]
		public string value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class staticLogFileName
	{

		private bool valueField;

		/// <remarks/>
		[XmlAttribute()]
		public bool value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class rollingStyle
	{

		private rollingStyleTypes valueField;

		/// <remarks/>
		[XmlAttribute()]
		public rollingStyleTypes value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	public enum rollingStyleTypes
	{

		/// <remarks/>
		Once,

		/// <remarks/>
		Size,

		/// <remarks/>
		Date,

		/// <remarks/>
		Composite,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class size
	{

		private int valueField;

		/// <remarks/>
		[XmlAttribute()]
		public int value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class scale
	{

		private byte valueField;

		/// <remarks/>
		[XmlAttribute()]
		public byte value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class precision
	{

		private byte valueField;

		/// <remarks/>
		[XmlAttribute()]
		public byte value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class conversionPattern
	{

		private string valueField;

		/// <remarks/>
		[XmlAttribute()]
		public string value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class ignoresException
	{

		private bool valueField;

		/// <remarks/>
		[XmlAttribute()]
		public bool value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class footer
	{

		private string valueField;

		/// <remarks/>
		[XmlAttribute()]
		public string value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class header
	{

		private string valueField;

		/// <remarks/>
		[XmlAttribute()]
		public string value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class base64EncodeMessage
	{

		private bool valueField;

		/// <remarks/>
		[XmlAttribute()]
		public bool value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class base64EncodeProperties
	{

		private bool valueField;

		/// <remarks/>
		[XmlAttribute()]
		public bool value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class layout
	{

		private object[] itemsField;

		private string typeField;

		private string valueField;

		/// <remarks/>
		[XmlElement("base64EncodeMessage", typeof(base64EncodeMessage), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("base64EncodeProperties", typeof(base64EncodeProperties), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("conversionPattern", typeof(conversionPattern), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("footer", typeof(footer), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("header", typeof(header), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("ignoresException", typeof(ignoresException), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("key", typeof(key), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("param", typeof(param), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public object[] Items
		{
			get { return this.itemsField; }
			set { this.itemsField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string type
		{
			get { return this.typeField; }
			set { this.typeField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class parameterName
	{

		private string valueField;

		/// <remarks/>
		[XmlAttribute()]
		public string value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class dbType
	{

		private DbType valueField;

		/// <remarks/>
		[XmlAttribute()]
		public DbType value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	public enum DbType
	{

		/// <remarks/>
		AnsiString,

		/// <remarks/>
		Binary,

		/// <remarks/>
		Byte,

		/// <remarks/>
		Boolean,

		/// <remarks/>
		Currency,

		/// <remarks/>
		Date,

		/// <remarks/>
		DateTime,

		/// <remarks/>
		Decimal,

		/// <remarks/>
		Double,

		/// <remarks/>
		Guid,

		/// <remarks/>
		Int16,

		/// <remarks/>
		Int32,

		/// <remarks/>
		Int64,

		/// <remarks/>
		Object,

		/// <remarks/>
		SByte,

		/// <remarks/>
		Single,

		/// <remarks/>
		String,

		/// <remarks/>
		Time,

		/// <remarks/>
		UInt16,

		/// <remarks/>
		UInt32,

		/// <remarks/>
		UInt64,

		/// <remarks/>
		VarNumeric,

		/// <remarks/>
		AnsiStringFixedLength,

		/// <remarks/>
		StringFixedLength,

		/// <remarks/>
		Xml,

		/// <remarks/>
		DateTime2,

		/// <remarks/>
		DateTimeOffset,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class parameter
	{

		private object[] itemsField;

		/// <remarks/>
		[XmlElement("dbType", typeof(dbType), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("layout", typeof(layout), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("parameterName", typeof(parameterName), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("precision", typeof(precision), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("scale", typeof(scale), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("size", typeof(size), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public object[] Items
		{
			get { return this.itemsField; }
			set { this.itemsField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class maximumFileSize
	{

		private string valueField;

		/// <remarks/>
		[XmlAttribute()]
		public string value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class maxFileSize
	{

		private long valueField;

		/// <remarks/>
		[XmlAttribute()]
		public long value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class datePattern
	{

		private string valueField;

		/// <remarks/>
		[XmlAttribute()]
		public string value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class countDirection
	{

		private countDirectionTypes valueField;

		/// <remarks/>
		[XmlAttribute()]
		public countDirectionTypes value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	public enum countDirectionTypes
	{

		/// <remarks/>
		[XmlEnum("-1")]
		Item1,

		/// <remarks/>
		[XmlEnum("1")]
		Item11,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class sink
	{

		private string valueField;

		/// <remarks/>
		[XmlAttribute(DataType = "anyURI")]
		public string value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class server
	{

		private string valueField;

		/// <remarks/>
		[XmlAttribute()]
		public string value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class sender
	{

		private string valueField;

		/// <remarks/>
		[XmlAttribute()]
		public string value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class recipient
	{

		private string valueField;

		/// <remarks/>
		[XmlAttribute()]
		public string value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class identity
	{

		private string valueField;

		/// <remarks/>
		[XmlAttribute()]
		public string value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class lockingModel
	{

		private lockingModelTypes typeField;

		/// <remarks/>
		[XmlAttribute()]
		public lockingModelTypes type
		{
			get { return this.typeField; }
			set { this.typeField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	public enum lockingModelTypes
	{

		/// <remarks/>
		[XmlEnum("log4net.Appender.FileAppender+ExclusiveLock")]
		log4netAppenderFileAppenderExclusiveLock,

		/// <remarks/>
		[XmlEnum("log4net.Appender.FileAppender+MinimalLock")]
		log4netAppenderFileAppenderMinimalLock,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class file
	{

		private string valueField;

		private string typeField;

		/// <remarks/>
		[XmlAttribute()]
		public string value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string type
		{
			get { return this.typeField; }
			set { this.typeField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class encoding
	{

		private encodingTypes valueField;

		/// <remarks/>
		[XmlAttribute()]
		public encodingTypes value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	public enum encodingTypes
	{

		/// <remarks/>
		[XmlEnum("us-ascii")]
		usascii,

		/// <remarks/>
		[XmlEnum("utf-7")]
		utf7,

		/// <remarks/>
		[XmlEnum("utf-8")]
		utf8,

		/// <remarks/>
		[XmlEnum("utf-16")]
		utf16,

		/// <remarks/>
		unicodeFFFE,

		/// <remarks/>
		[XmlEnum("utf-32")]
		utf32,

		/// <remarks/>
		[XmlEnum("utf-32BE")]
		utf32BE,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class machineName
	{

		private string valueField;

		/// <remarks/>
		[XmlAttribute()]
		public string value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class logName
	{

		private string valueField;

		/// <remarks/>
		[XmlAttribute()]
		public string value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class applicationName
	{

		private string valueField;

		/// <remarks/>
		[XmlAttribute()]
		public string value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class immediateFlush
	{

		private bool valueField;

		/// <remarks/>
		[XmlAttribute()]
		public bool value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class backColor
	{

		private allColorTypes valueField;

		/// <remarks/>
		[XmlAttribute()]
		public allColorTypes value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	public enum allColorTypes
	{

		/// <remarks/>
		Black,

		/// <remarks/>
		Blue,

		/// <remarks/>
		Cyan,

		/// <remarks/>
		Green,

		/// <remarks/>
		HighIntensity,

		/// <remarks/>
		Magenta,

		/// <remarks/>
		Purple,

		/// <remarks/>
		Red,

		/// <remarks/>
		White,

		/// <remarks/>
		Yellow,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class attributes
	{

		private attributesTypes valueField;

		/// <remarks/>
		[XmlAttribute()]
		public attributesTypes value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	public enum attributesTypes
	{

		/// <remarks/>
		Bright,

		/// <remarks/>
		Dim,

		/// <remarks/>
		Underscore,

		/// <remarks/>
		Blink,

		/// <remarks/>
		Reverse,

		/// <remarks/>
		Hidden,

		/// <remarks/>
		Strikethrough,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class severity
	{

		private severityTypes valueField;

		/// <remarks/>
		[XmlAttribute()]
		public severityTypes value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	public enum severityTypes
	{

		/// <remarks/>
		Emergency,

		/// <remarks/>
		Alert,

		/// <remarks/>
		Critical,

		/// <remarks/>
		Error,

		/// <remarks/>
		Warning,

		/// <remarks/>
		Notice,

		/// <remarks/>
		Informational,

		/// <remarks/>
		Debug,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class eventLogEntryType
	{

		private EventLogEntryType valueField;

		/// <remarks/>
		[XmlAttribute()]
		public EventLogEntryType value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	public enum EventLogEntryType
	{

		/// <remarks/>
		Error,

		/// <remarks/>
		Warning,

		/// <remarks/>
		Information,

		/// <remarks/>
		SuccessAudit,

		/// <remarks/>
		FailureAudit,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class foreColor
	{

		private allColorTypes valueField;

		/// <remarks/>
		[XmlAttribute()]
		public allColorTypes value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class mapping
	{

		private object[] itemsField;

		/// <remarks/>
		[XmlElement("attributes", typeof(attributes), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("backColor", typeof(backColor), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("eventLogEntryType", typeof(eventLogEntryType), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("foreColor", typeof(foreColor), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("level", typeof(level), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("severity", typeof(severity), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public object[] Items
		{
			get { return this.itemsField; }
			set { this.itemsField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class level
	{

		private log4netLevel valueField;

		/// <remarks/>
		[XmlAttribute()]
		public log4netLevel value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class target
	{

		private consoleTargetTypes valueField;

		/// <remarks/>
		[XmlAttribute()]
		public consoleTargetTypes value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	public enum consoleTargetTypes
	{

		/// <remarks/>
		[XmlEnum("Console.Out")]
		ConsoleOut,

		/// <remarks/>
		[XmlEnum("Console.Error")]
		ConsoleError,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class useTransactions
	{

		private bool valueField;

		/// <remarks/>
		[XmlAttribute()]
		public bool value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class reconnectOnError
	{

		private bool valueField;

		/// <remarks/>
		[XmlAttribute()]
		public bool value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class facility
	{

		private facilityTypes valueField;

		/// <remarks/>
		[XmlAttribute()]
		public facilityTypes value
		{
			get { return this.valueField; }
			set { this.valueField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	public enum facilityTypes
	{

		/// <remarks/>
		Kernel,

		/// <remarks/>
		User,

		/// <remarks/>
		Mail,

		/// <remarks/>
		Daemons,

		/// <remarks/>
		Authorization,

		/// <remarks/>
		Syslog,

		/// <remarks/>
		Printer,

		/// <remarks/>
		News,

		/// <remarks/>
		Uucp,

		/// <remarks/>
		Clock,

		/// <remarks/>
		Authorization2,

		/// <remarks/>
		Ftp,

		/// <remarks/>
		Ntp,

		/// <remarks/>
		Audit,

		/// <remarks/>
		Alert,

		/// <remarks/>
		Clock2,

		/// <remarks/>
		Local0,

		/// <remarks/>
		Local1,

		/// <remarks/>
		Local2,

		/// <remarks/>
		Local3,

		/// <remarks/>
		Local4,

		/// <remarks/>
		Local5,

		/// <remarks/>
		Local6,

		/// <remarks/>
		Local7,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class root
	{

		private object[] itemsField;

		/// <remarks/>
		[XmlElement("appender-ref", typeof(appender_ref), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("level", typeof(level), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("param", typeof(param), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public object[] Items
		{
			get { return this.itemsField; }
			set { this.itemsField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class appender_ref
	{

		private string refField;

		/// <remarks/>
		[XmlAttribute()]
		public string @ref
		{
			get { return this.refField; }
			set { this.refField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class renderer
	{

		private string renderingClassField;

		private string renderedClassField;

		/// <remarks/>
		[XmlAttribute()]
		public string renderingClass
		{
			get { return this.renderingClassField; }
			set { this.renderingClassField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string renderedClass
		{
			get { return this.renderedClassField; }
			set { this.renderedClassField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class logger
	{

		private object[] itemsField;

		private string nameField;

		private bool additivityField;

		public logger()
		{
			this.additivityField = true;
		}

		/// <remarks/>
		[XmlElement("appender-ref", typeof(appender_ref), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("level", typeof(level), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[XmlElement("param", typeof(param), Form =
			System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public object[] Items
		{
			get { return this.itemsField; }
			set { this.itemsField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		public string name
		{
			get { return this.nameField; }
			set { this.nameField = value; }
		}

		/// <remarks/>
		[XmlAttribute()]
		[System.ComponentModel.DefaultValueAttribute(true)]
		public bool additivity
		{
			get { return this.additivityField; }
			set { this.additivityField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	public enum log4netAppenderTypes
	{

		/// <remarks/>
		[XmlEnum("log4net.Appender.AdoNetAppender")]
		log4netAppenderAdoNetAppender,

		/// <remarks/>
		[XmlEnum("log4net.Appender.AnsiColorTerminalAppender")]
		log4netAppenderAnsiColorTerminalAppender,

		/// <remarks/>
		[XmlEnum("log4net.Appender.AspNetTraceAppender")]
		log4netAppenderAspNetTraceAppender,

		/// <remarks/>
		[XmlEnum("log4net.Appender.BufferingForwardingAppender")]
		log4netAppenderBufferingForwardingAppender,

		/// <remarks/>
		[XmlEnum("log4net.Appender.ColoredConsoleAppender")]
		log4netAppenderColoredConsoleAppender,

		/// <remarks/>
		[XmlEnum("log4net.Appender.ConsoleAppender")]
		log4netAppenderConsoleAppender,

		/// <remarks/>
		[XmlEnum("log4net.Appender.DebugAppender")]
		log4netAppenderDebugAppender,

		/// <remarks/>
		[XmlEnum("log4net.Appender.EventLogAppender")]
		log4netAppenderEventLogAppender,

		/// <remarks/>
		[XmlEnum("log4net.Appender.FileAppender")]
		log4netAppenderFileAppender,

		/// <remarks/>
		[XmlEnum("log4net.Appender.ForwardingAppender")]
		log4netAppenderForwardingAppender,

		/// <remarks/>
		[XmlEnum("log4net.Appender.LocalSyslogAppender")]
		log4netAppenderLocalSyslogAppender,

		/// <remarks/>
		[XmlEnum("log4net.Appender.MemoryAppender")]
		log4netAppenderMemoryAppender,

		/// <remarks/>
		[XmlEnum("log4net.Appender.NetSendAppender")]
		log4netAppenderNetSendAppender,

		/// <remarks/>
		[XmlEnum("log4net.Appender.OutputDebugStringAppender")]
		log4netAppenderOutputDebugStringAppender,

		/// <remarks/>
		[XmlEnum("log4net.Appender.RemoteSyslogAppender")]
		log4netAppenderRemoteSyslogAppender,

		/// <remarks/>
		[XmlEnum("log4net.Appender.RemotingAppender")]
		log4netAppenderRemotingAppender,

		/// <remarks/>
		[XmlEnum("log4net.Appender.RollingFileAppender")]
		log4netAppenderRollingFileAppender,

		/// <remarks/>
		[XmlEnum("log4net.Appender.SmtpAppender")]
		log4netAppenderSmtpAppender,

		/// <remarks/>
		[XmlEnum("log4net.Appender.SmtpPickupDirAppender")]
		log4netAppenderSmtpPickupDirAppender,

		/// <remarks/>
		[XmlEnum("log4net.Appender.TelnetAppender")]
		log4netAppenderTelnetAppender,

		/// <remarks/>
		[XmlEnum("log4net.Appender.TextWriterAppender")]
		log4netAppenderTextWriterAppender,

		/// <remarks/>
		[XmlEnum("log4net.Appender.TraceAppender")]
		log4netAppenderTraceAppender,

		/// <remarks/>
		[XmlEnum("log4net.Appender.UdpAppender")]
		log4netAppenderUdpAppender,

        /// <remarks/>
		[XmlEnum("Sonata.Diagnostics.Logging.Appenders.AdoNetAppender, Sonata.Diagnostics")]
        SonataDiagnosticsLoggingAppendersAdoNetAppender
    }

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
	[System.SerializableAttribute()]
	public enum log4netUpdateAttribute
	{

		/// <remarks/>
		Merge,

		/// <remarks/>
		Overwrite,
	}
}